from enum import Enum


class ConnectorState(str, Enum):
    DECLARED = "DECLARED"
    TOOL_SCHEMA_DISCOVERED = "TOOL_SCHEMA_DISCOVERED"
    AUTH_FLOW_PRESENT = "AUTH_FLOW_PRESENT"
    AUTHENTICATED = "AUTHENTICATED"
    IDENTITY_RESOLVED = "IDENTITY_RESOLVED"
    WORKSPACE_RESOLVED = "WORKSPACE_RESOLVED"
    CAPABILITIES_DISCOVERED = "CAPABILITIES_DISCOVERED"
    READ_VERIFIED = "READ_VERIFIED"
    WRITE_PREFLIGHT_VERIFIED = "WRITE_PREFLIGHT_VERIFIED"
    EVENT_SYNC_VERIFIED = "EVENT_SYNC_VERIFIED"
    POLICY_ADMISSIBLE = "POLICY_ADMISSIBLE"
    ORCHESTRATION_READY = "ORCHESTRATION_READY"


class ConnectorSubstate(str, Enum):
    NONE = "NONE"
    PASS_EMPTY = "PASS_EMPTY"
    REQUIRES_REAUTHORIZATION = "REQUIRES_REAUTHORIZATION"
    REQUIRES_PERMISSION = "REQUIRES_PERMISSION"
    REQUIRES_PLAN_UPGRADE = "REQUIRES_PLAN_UPGRADE"
    ACCOUNT_NOT_CREATED = "ACCOUNT_NOT_CREATED"
    UI_ONLY = "UI_ONLY"
    SCHEMA_ONLY = "SCHEMA_ONLY"
    RUNTIME_TOOL_MISSING = "RUNTIME_TOOL_MISSING"
    RATE_LIMITED = "RATE_LIMITED"
    DEGRADED = "DEGRADED"
    BLOCKED = "BLOCKED"
    MANUAL_VERIFICATION_REQUIRED = "MANUAL_VERIFICATION_REQUIRED"
